# connection tracking helpers

# rtsp protocol support
obj-$(CONFIG_IP_NF_RTSP) += ip_conntrack_rtsp.o
ifdef CONFIG_IP_NF_NAT_RTSP
       export-objs += ip_conntrack_rtsp.o
endif
obj-$(CONFIG_IP_NF_NAT_RTSP) += ip_nat_rtsp.o

